lib/src/settings.dart
tool/clean_commands.dart

feat: tool script to clean the registered commands specific to a guild, usually implemented in a development environment
chore: adapted intents to always be the same

feat: production dockerization

---

lib/src/commands/radio.dart
lib/src/services/music.dart

feat: replacing tracks with radio when played, and added handler for track events

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.devcontainer/library-scripts/common-debian.sh
.gitignore
README.md

This PR adds all the config to run the project on a dev container, thus making development much faster by not rebuilding the docker every time there's a change.

Dev workspace working 😎

---

.github/workflows/radio_garden.yaml
lib/src/commands/commands.dart
lib/src/commands/music.dart
lib/src/commands/radio.dart
lib/src/models/radio_garden_response.dart
lib/src/models/song_recognition.dart
lib/src/models/song_recognition.freezed.dart
lib/src/services/music.dart
lib/src/settings.dart
pubspec.yaml

feat: autocomplete for radio

---

lib/src/commands/info.dart
pubspec.yaml

fix: `/info` command type error

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/build.md
.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/ci.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/performance.md
.github/ISSUE_TEMPLATE/refactor.md
.github/ISSUE_TEMPLATE/revert.md
.github/ISSUE_TEMPLATE/style.md
.github/ISSUE_TEMPLATE/test.md
.github/PULL_REQUEST_TEMPLATE.md

**Description**
Adds issue and pull request templates.

chore: added github templates

---

.github/hooks/commit-msg
.github/hooks/pre-commit
.vscode/settings.json
.vscode/tasks.json
lavalink.yml
pubspec.yaml

**READY**
This PR includes hooks for ensuring we uphold standards even before we commit.

chore(hooks): pre-commit and commit-msg

---

build.yaml
lib/i18n/strings.g.dart
lib/i18n/strings.i18n.json
lib/i18n/strings_es.i18n.json
lib/radio_garden.dart
lib/src/commands/commands.dart
lib/src/commands/info.dart
lib/src/commands/music.dart
lib/src/commands/radio.dart
lib/src/error_handler.dart
lib/src/services/music.dart
lib/src/util.dart
pubspec.yaml

**READY**
Adds translations for all commands, services, and error handlers which need it in Spanish and English. 
Translations working!

feat: translations in english and spanish

---

lib/i18n/strings.g.dart
lib/i18n/strings.i18n.json
lib/i18n/strings_es.i18n.json
lib/src/commands/info.dart

Adds the `current players` field to the `info` command of the bot.
**READY**

feat(info-command): add current players field

---

lib/i18n/strings.g.dart
lib/i18n/strings.i18n.json
lib/i18n/strings_es.i18n.json
lib/src/commands/info.dart

**READY**
- Adds the "Gateway Latency" translations.
- Adds to the `/info` command the gateway latency.
- Closes #13

feat(command-info): gateway latency added

---

bin/radio_garden_development.dart
bin/radio_garden_production.dart
lib/i18n/strings.g.dart
lib/i18n/strings.i18n.json
lib/i18n/strings_es.i18n.json
lib/src/checks.dart
lib/src/commands/commands.dart
lib/src/services/music.dart
lib/src/version.dart

feat: leave channel when nobody's listening

---

bin/radio_garden_development.dart
bin/radio_garden_production.dart

**READY**
Adds log configurations to include most logs, so we can backtrace errors and exceptions better.

feat: fine logs

---

relaunch_prod.bat
relaunch_prod.sh

fix: bad config in relaunch_prod.sh

---

lib/i18n/strings.i18n.json

fix: localization on info command

---

.github/workflows/dart_package.yaml
CHANGELOG.md
lib/i18n/strings.g.dart
lib/i18n/strings.i18n.json
lib/i18n/strings_es.i18n.json
lib/src/commands/radio.dart
lib/src/models/shazam_song_recognition/shazam_result.dart
lib/src/models/song_recognition/current_station_info.dart
lib/src/models/song_recognition/current_station_info.g.dart
lib/src/services/song_recognition.dart
lib/src/version.dart
pubspec.yaml

**READY**
Adds functionality to get the song's info from the URL instead of the shazam endpoint.

feat: shazamless song info

---

bin/radio_horizon_development.dart
bin/radio_horizon_production.dart
lib/src/commands/commands.dart
lib/src/services/bootup.dart

**READY**
- Bootup system now takes into account the delay in the connection to Lavalink
- Fixed the sound commands not showing up

fix: bootup not playing radios

---

lib/src/models/song_recognition/current_station_info.dart
lib/src/models/song_recognition/current_station_info.g.dart
lib/src/services/song_recognition.dart

**READY**
- Migrated to Radiolise Service: https://gitlab.com/radiolise/deprecated-service
- Migrated (again) to the new API for music links (temporary).

feat: migrated to radiolise service to get current station information

---

lib/src/services/music.dart

**READY**
This PR removes the functionality of leaving a voice channel.

chore: remove leaving behaviour

---

lib/src/commands/music.dart
lib/src/commands/radio.dart
lib/src/commands/sound.dart

style: dart format

---

docker-compose.prod.yml

fix: added lavalink 3 constraint to docker compose prod

---

.env.vault
.github/hooks/pre-commit
bin/radio_horizon_development.dart
bin/radio_horizon_production.dart
lib/src/commands/info.dart
lib/src/commands/music.dart
lib/src/commands/radio.dart
lib/src/commands/sound.dart
lib/src/services/music.dart
lib/src/settings.dart
pubspec.yaml

**READY**
Adds implementation to support Sentry logging and reporting.

feat: sentry reporting

---

.env.vault
.github/hooks/pre-commit
bin/radio_horizon_development.dart
bin/radio_horizon_production.dart
lib/src/commands/info.dart
lib/src/commands/music.dart
lib/src/commands/radio.dart
lib/src/commands/sound.dart
lib/src/services/music.dart
lib/src/settings.dart
pubspec.yaml

fix: initialization reversed

---

bin/radio_horizon_production.dart
lib/src/settings.dart
lib/src/version.dart
pubspec.yaml

**READY**
Fixes the issue that doesn't let the bot start.

fix: not booting

---

lib/i18n/strings.g.dart
lib/i18n/strings.i18n.json
lib/i18n/strings_es.i18n.json
lib/src/commands/radio.dart

**READY**
Closes #84 
Closes #82

feat(radio): upvote and click station

---

lib/src/services/music.dart

**READY**
We were getting a false positive exception in Sentry caused by this.

fix: false positive exception

---

lib/i18n/strings.g.dart
lib/i18n/strings.i18n.json
lib/i18n/strings_es.i18n.json
lib/src/commands/radio.dart
lib/src/helpers/random_string.dart

feat: random radio
